{
    'name': 'Sunartha Accounting Base',
    'version': '18.0.1.0.0',
    'category': 'Accounting/Accounting',
    'summary': 'Fondasi akuntansi PSAK Indonesia — COA, PPh/PPN, approval jurnal, laporan PSAK 1 & 2',
    'author': 'Sunartha',
    'website': 'https://sunartha.co.id',
    'depends': [
        'account',
        'l10n_id',
        'mail',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/account_account_data.xml',
        'data/account_tax_data.xml',
        'views/account_approval_request_views.xml',
        'views/account_approval_reject_wizard_views.xml',
        'views/account_journal_views.xml',
        'views/account_move_views.xml',
        'views/menu.xml',
        'reports/report_action.xml',
        'reports/report_posisi_keuangan.xml',
        'reports/report_laba_rugi.xml',
        'reports/report_arus_kas.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
